### ISSUE TITLE
When I try to build the current github repo from source I get the errors

### ISSUE THREAD

**Issue by nilslacroix** [intel/scikit-learn-intelex#1001]
**Describe the bug**
When I try to build the current github repo from source in anaconda I get this error in my notebook:

cannot import name '_num_samples' from 'onedal.datatypes'  when trying to use patch_sklearn().
I installed this with the manual from the homepage and daal4py is installed.

**Environment:**
 - Windows 10
 - Anaconda miniconda3 enviroment (newest version)
 - Latest Github Scikit Intelex repo

**Comment by napetrov** [comment]
@nilslacroix  - could you please describe steps that you are doing? 

This configuration is validated as part of publicCI, so it works in general although master state doesn't guarantee that all things would be working - please use releases for that. 

Could you please cover why you need build from source instead of using prebuild version?
