### ISSUE TITLE
No 2021.6.0 version available for pip installation

### ISSUE THREAD

**Issue by L-Marriott** [intel/scikit-learn-intelex#1003]
**Describe the bug**

Cannot install newest version through pip. Prior versions are available.

**To Reproduce**

pip install scikit-learn-intelex==2021.6.0

**Expected behavior**

Expecting to install v6.0, 

**Output/Screenshots**

![image](https://user-images.githubusercontent.com/88332350/167381181-2cc19011-993c-4f93-a42b-04e23d9911ee.png)

**Environment:**
Pip is up to date (22.0.4)
Python 3.9

**Comment by Alexsandruss** [comment]
Newest scikit-learn-intelex 2021.6.3 is [available on pip](https://pypi.org/project/scikit-learn-intelex/2021.6.3/#files).
However, it has [issue with scikit-learn>=1.1](https://github.com/intel/scikit-learn-intelex/issues/1018) which will be fixed in next release. You can use lower scikit-learn versions as temporary fix.
