### ISSUE TITLE
TypeError: _check_sample_weight() got an unexpected keyword argument 'copy'

### ISSUE THREAD

**Issue by guankaer** [intel/scikit-learn-intelex#1017]
TypeError: _check_sample_weight() got an unexpected keyword argument 'copy'

**Comment by samir-nasibli** [comment]
Hi @guankaer could you please provide more details about python env. python, sklearn, sklearnex versions

**Comment by Alexsandruss** [comment]
Hi @guankaer, could you provide some code + OS, python, sklearn and sklearnex versions to reproduce this issue, please?

**Comment by ltoropova** [comment]
Hi, I faced the same problem and it seems that the root cause is that [here](https://github.com/intel/scikit-learn-intelex/blob/develop/daal4py/sklearn/linear_model/logistic_path.py#L284) in case if sklearn version is greater or equal to 0.24, 'copy' argument is used, however it was introduced for [_check_sample_weight](https://github.com/scikit-learn/scikit-learn/blob/0.24.2/sklearn/utils/validation.py#L1333) only in 0.24.2. 
So this problem occurs only for sklearn 0.24 and 0.24.1

**Comment by napetrov** [comment]
Thanks - the expectation is that latest past releases would be used.
