### ISSUE TITLE
Could not find a version that satisfies the requirement scikit-learn-intelex. 

### ISSUE THREAD

**Issue by dawikrol** [intel/scikit-learn-intelex#2105]
When I try to install: `pip install scikit-learn-intelex` I get: 

> ERROR: Could not find a version that satisfies the requirement scikit-learn-intelex (from versions: none)
> ERROR: No matching distribution found for scikit-learn-intelex

pip: 24.2
python: 3.9, 3.11, 3.12
env: os 14.6

**Comment by Alexsandruss** [comment]
Does `env: os 14.6` refer to macOS? If so, what CPU arch are you using (arm64 or x86-64)?

In case of arm64, sklearnex never supported it, otherwise, you should be able to download older releases of sklearnex from PyPI or conda-forge channel since macOS support was dropped starting from 2024.0 version ([2023.2.* release](https://github.com/intel/scikit-learn-intelex/releases/tag/2023.2.0) was last to support it).
