### ISSUE TITLE
Code quality improvements - adress findings from www.codefactor.io

### ISSUE THREAD

**Issue by napetrov** [intel/scikit-learn-intelex#800]
Please create PRs for addressing code quality issues reported by codefactor scans

https://www.codefactor.io/repository/github/intel/scikit-learn-intelex

Some problems are simple fixes and i would expect that they can be fixed across entire repo and not one by one
Other might be super complex and i don't think can be fixed without serious refactoring - code complexity

**Comment by anuragphadnis** [comment]
Since one PR won't be sufficient for the complete work, I would like to start working by removing all "unnecessary elif" first and later can work on fixing other issues if no one else start working on them. To get started can you provide me with document with steps to initialize & test the project, steps to check code quality from codefactor.io for my fork of this repository, and guidelines to contribute.

**Comment by napetrov** [comment]
@anuragphadnis  - thanks please go ahead with fixing subset of hits. 

codefactor checks are baked in precommit and you can use it for validation once you will open PR.  Same can be used for tests.

**Comment by anuragphadnis** [comment]
ok I will start and let you know if I face any issue.

**Comment by anuragphadnis** [comment]
Hi, I have created the [PR](https://github.com/intel/scikit-learn-intelex/pull/801) but I need help to understand why 2 test cases are failing.

**Comment by napetrov** [comment]
@anuragphadnis  - thanks - there are PEP8 failures if your PR. There is new line required 

./daal4py/sklearn/_device_offload.py:85:9: E306 expected 1 blank line before a nested definition, found 0

**Comment by anuragphadnis** [comment]
> 
> 
> @anuragphadnis - thanks - there are PEP8 failures if your PR. There is new line required
> 
> ./daal4py/sklearn/_device_offload.py:85:9: E306 expected 1 blank line before a nested definition, found 0

Thanks, I have fixed it, please check.
