### ISSUE TITLE
No speed up when using patch_sklearn with PyCaret

### ISSUE THREAD

**Issue by moezali1** [intel/scikit-learn-intelex#996]
Hi,

We are planning to integrate scikit-learn-intelex project with [PyCaret](https://www.github.com/pycaret/pycaret)

The issue is as following:

```
from pycaret.datasets import get_data
data = get_data('poker')

from pycaret.classification import *
s = setup(data, target = 'CLASS', session_id = 123)

from sklearnex import patch_sklearn
patch_sklearn()

%%time
knn = create_model('knn')
```
![image](https://user-images.githubusercontent.com/54699234/162780527-65069d98-8134-425a-be0b-bcdfa0f06607.png)

This took 10 minute despite of `patch_sklearn` command.

However when I explicitly import the model it gives great results from acceleration:

```
from pycaret.datasets import get_data
data = get_data('poker')

from pycaret.classification import *
s = setup(data, target = 'CLASS', session_id = 123)

from sklearnex import patch_sklearn
patch_sklearn()

from sklearn.neighbors import KNeighborsClassifier
knn_intel = KNeighborsClassifier()

%%time
knn_intel = create_model(knn_intel)
```
![image](https://user-images.githubusercontent.com/54699234/162780685-5237f20a-ae73-4478-a053-e7edbac73638.png)

## Expected Action:
What can we do to make the first attempt gives result of acceleration so that users won't have to import estimator explicitly. I am thinking we can add a parameter in the `setup` function called `use_intel_acceleration`. When that is set to `True` by user we should run `patch_sklearn` command in our code base so that users won't have to do any thing explicitly outside of PyCaret code base.

The file which creates model container in PyCaret repo are [located here](https://github.com/pycaret/pycaret/tree/master/pycaret/containers/models).

**Comment by PivovarA** [comment]
Hi @moezali1 
Thanks for reporting the issue.
The problem is that patching must be applied before calling **sklearn**. patching replaces some methods from **sklearn** with their optimizions from the **intel extension for scikit-learn**.
In your case, you are importing pycaret first, where sklearn is already imported.
However, I found that if you call the patch before all other code, your code that you have attached will not work. This is not expected behavior.
The reason for this is a bug on our side, which is related to **train_test_split**. I already created an [issue](https://github.com/intel/scikit-learn-intelex/issues/997)
I already have a fix and I will create a PR with it in the near future. After the fix everything seems to work as expected:

<img width="1031" alt="Снимок экрана 2022-04-12 в 12 50 55" src="https://user-images.githubusercontent.com/55380278/162944297-c0c747f7-3ea4-4249-835f-2da9cb429d76.png">

<img width="1027" alt="Снимок экрана 2022-04-12 в 12 51 06" src="https://user-images.githubusercontent.com/55380278/162944321-1b267dc1-da75-447e-b48c-4621e92c51fc.png">

We also think that the patching option may not be the easiest for integration and perhaps the best option would be to import the required methods directly from **sklearnex**. The **autogluon** team integrated sklearnex in a [similar way](https://github.com/awslabs/autogluon/blob/a7e7fa624fb6980fffc6dd320ee2cc15f0b99879/tabular/src/autogluon/tabular/models/rf/rf_model.py#L45).

**Comment by PivovarA** [comment]
@moezali1 
Also like an option you can use patching for some algorithms.
For example this line will work for your code:

```
from sklearnex import patch_sklearn
patch_sklearn("knn_classifier")

from pycaret.datasets import get_data
data = get_data('poker')

from pycaret.classification import *
s = setup(data, target = 'CLASS', session_id = 126)
```

<img width="1018" alt="Снимок экрана 2022-04-12 в 14 32 26" src="https://user-images.githubusercontent.com/55380278/162963122-cb4395c0-b08a-4a1d-91fb-c4fe0a902816.png">

<img width="1021" alt="Снимок экрана 2022-04-12 в 14 32 35" src="https://user-images.githubusercontent.com/55380278/162963139-ae70441f-e049-41b0-a47c-87aeb27b77ba.png">

To get map of algorithms:

```
import daal4py as d4p
d4p.sklearn.monkeypatch.dispatcher._get_map_of_algorithms().keys()

>>
dict_keys(['pca', 'kmeans', 'dbscan', 'distances', 'linear', 'ridge', 'elasticnet', 'lasso', 'svm', 'logistic', 'log_reg', 'knn_classifier', 'nearest_neighbors', 'knn_regressor', 'random_forest_classifier', 'random_forest_regressor', 'train_test_split', 'fin_check', 'roc_auc_score', 'tsne', 'svc', 'logisticregression', 'kneighborsclassifier', 'nearestneighbors', 'kneighborsregressor', 'randomrorestclassifier', 'randomforestregressor'])
```
 I can also help you create a PR for integration **sklearnex** into **pycaret**.

**Comment by moezali1** [comment]
@PivovarA Thanks for your detailed response. I look forward to receiving your PR on pycaret. Excited for this integration.

**Comment by moezali1** [comment]
@PivovarA We are releasing 3.0-rc in 2 weeks. Do you think its possible to send a PR our way on `develop` branch before May 15th?

Thanks.
